title: Vishnu Murali Krishnan
description: Personal portfolio
url: https://vishnumkpn.github.io
baseurl:

theme: minima
google_analytics: G-QHTYH0M9C2

plugins:
  - jekyll-seo-tag
  - jekyll-feed

nav:
  - title: Projects
    url: /projects/
